package com.example.sololearnclone.fragments.lessons

import android.graphics.Color

enum class KotlinKeywords(val color: Int) {
    BREAK(Color.RED),
    CLASS(Color.RED),
    CONTINUE(Color.RED),
    DO(Color.RED),
    ELSE(Color.RED),
    FALSE(Color.RED),
    FOR(Color.RED),
    FUN(Color.RED),
    IF(Color.RED),
    INTERFACE(Color.RED),
    NULL(Color.RED),
    OBJECT(Color.RED),
    PACKAGE(Color.RED),
    RETURN(Color.RED),
    SUPER(Color.RED),
    THIS(Color.RED),
    THROW(Color.RED),
    TRUE(Color.RED),
    TRY(Color.RED),
    TYPEALIAS(Color.RED),
    VAL(Color.RED),
    VAR(Color.RED),
    WHEN(Color.RED),

    BY(Color.BLUE),
    CATCH(Color.BLUE),
    CONSTRUCTOR(Color.BLUE),
    FIELD(Color.BLUE),
    FINALLY(Color.BLUE),
    GET(Color.BLUE),
    IMPORT(Color.BLUE),
    INIT(Color.BLUE),
    WHERE(Color.BLUE),

    ABSTRACT(Color.GREEN),
    ACTUAL(Color.GREEN),
    ANNOTATION(Color.GREEN),
    CONST(Color.GREEN),
    CROSSINLINE(Color.GREEN),
    DATA(Color.GREEN),
    ENUM(Color.GREEN),
    EXPECT(Color.GREEN),
    EXTERNAL(Color.GREEN),
    FINAL(Color.GREEN),
    INFIX(Color.GREEN),
    INLINE(Color.GREEN),
    INTERNAL(Color.GREEN),
    LATEINIT(Color.GREEN),
    NOINLINE(Color.GREEN),
    OPEN(Color.GREEN),
    OPERATOR(Color.GREEN),
    OUT(Color.GREEN),
    OVERRIDE(Color.GREEN),
    PRIVATE(Color.GREEN),
    PROTECTED(Color.GREEN),
    PUBLIC(Color.GREEN),
    REIFIED(Color.GREEN),
    SEALED(Color.GREEN),
    SUSPEND(Color.GREEN),
    TAILREC(Color.GREEN),
    VARARG(Color.GREEN),
}